// <auto-generated />
using System;
using EntityFramework_PIV_Projekt2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework_PIV_Projekt2.Migrations
{
    [DbContext(typeof(SystemBiletContext))]
    partial class SystemBiletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerBudynku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Bilety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Miejsce")
                        .HasColumnType("int");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WydarzenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WydarzenieId");

                    b.ToTable("Bilety");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Klienci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.KlienciBiletyTransakcje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiletId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataZakupu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscZakupionychBiletow")
                        .HasColumnType("int");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("MetodaPlatnosci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RabatKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RezerwacjaId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BiletId");

                    b.HasIndex("KlientId");

                    b.HasIndex("RabatKod");

                    b.HasIndex("RezerwacjaId");

                    b.ToTable("Transakcje");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Miejsca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("NazwaObiektu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ZdjecieObiektu")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Miejsca");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Oceny", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Komentarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ocena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WydarzenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("WydarzenieId");

                    b.ToTable("Oceny");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Organizatorzy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaFirmy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Organizatorzy");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Rabat", b =>
                {
                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Znizka")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Kod");

                    b.ToTable("Rabaty");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Rezerwacje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaRezerwacji")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataRezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DlugoscRezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Wydarzenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaBiletu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscBiletow")
                        .HasColumnType("int");

                    b.Property<int?>("MiejsceId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Plakat")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiejsceId");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("Wydarzenia");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Bilety", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Wydarzenie", "Wydarzenie")
                        .WithMany("Bilet")
                        .HasForeignKey("WydarzenieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wydarzenie");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Klienci", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Adres", "Adres")
                        .WithMany("Kliencis")
                        .HasForeignKey("AdresId");

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.KlienciBiletyTransakcje", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Bilety", "Bilet")
                        .WithMany("KlienciBiletyTransakcjes")
                        .HasForeignKey("BiletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_PIV_Projekt2.Klienci", "Klient")
                        .WithMany("Transakcje")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_PIV_Projekt2.Rabat", "Rabat")
                        .WithMany("KlienciBiletyTransakcjes")
                        .HasForeignKey("RabatKod");

                    b.HasOne("EntityFramework_PIV_Projekt2.Rezerwacje", "Rezerwacja")
                        .WithMany("Transakcje")
                        .HasForeignKey("RezerwacjaId");

                    b.Navigation("Bilet");

                    b.Navigation("Klient");

                    b.Navigation("Rabat");

                    b.Navigation("Rezerwacja");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Miejsca", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Adres", "Adres")
                        .WithMany("Miejscas")
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Oceny", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Klienci", "Klient")
                        .WithMany("Oceny")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_PIV_Projekt2.Wydarzenie", "Wydarzenie")
                        .WithMany("Ocenies")
                        .HasForeignKey("WydarzenieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Wydarzenie");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Organizatorzy", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Adres", "Adres")
                        .WithMany("Organizatorzies")
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Rezerwacje", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Klienci", "Klient")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Wydarzenie", b =>
                {
                    b.HasOne("EntityFramework_PIV_Projekt2.Miejsca", "Miejsce")
                        .WithMany("Wydarzenia")
                        .HasForeignKey("MiejsceId");

                    b.HasOne("EntityFramework_PIV_Projekt2.Organizatorzy", "Organizator")
                        .WithMany("Wydarzenia")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miejsce");

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Adres", b =>
                {
                    b.Navigation("Kliencis");

                    b.Navigation("Miejscas");

                    b.Navigation("Organizatorzies");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Bilety", b =>
                {
                    b.Navigation("KlienciBiletyTransakcjes");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Klienci", b =>
                {
                    b.Navigation("Oceny");

                    b.Navigation("Rezerwacje");

                    b.Navigation("Transakcje");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Miejsca", b =>
                {
                    b.Navigation("Wydarzenia");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Organizatorzy", b =>
                {
                    b.Navigation("Wydarzenia");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Rabat", b =>
                {
                    b.Navigation("KlienciBiletyTransakcjes");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Rezerwacje", b =>
                {
                    b.Navigation("Transakcje");
                });

            modelBuilder.Entity("EntityFramework_PIV_Projekt2.Wydarzenie", b =>
                {
                    b.Navigation("Bilet");

                    b.Navigation("Ocenies");
                });
#pragma warning restore 612, 618
        }
    }
}
